---

- name: Add mongodb yum repository
  template:
    src:   mongodb.yum.repo.j2
    dest:  /etc/yum.repos.d/mongodb-org-{{ mongodb_repo_version }}.repo
    owner: root
    group: root
    mode:  0644

# https://docs.mongodb.com/v3.0/tutorial/install-mongodb-on-red-hat/#install-the-mongodb-packages-and-associated-tools
- name: Install mongodb
  yum:
    name:  "{{ item }}-{{ mongodb_version|default('*') }}"
    state: present
  with_items: 
    - mongodb-org
    - mongodb-org-server
    - mongodb-org-mongos
    - mongodb-org-shell
    - mongodb-org-tools
  notify: Restart mongodb

- name: RHEL | Set permissions and SELinux context on log and data directories
  file:
    path: "{{ item.path }}"
    owner: "{{ mongodb_user }}"
    group: "{{ mongodb_user }}"
    mode: 0755
    setype: "{{ item.type }}"
    state: directory
  with_items:
    - path: "{{ mongodb_data_dir }}"
      type: mongod_var_lib_t
    - path: "{{ mongodb_log_dir }}"
      type: mongod_log_t

- name: RHEL | Configure SELinux
  seport:
    ports: "{{ mongodb_net.port }}"
    proto: tcp
    setype: mongod_port_t
    state: present
